version: '3'

services:
  #MySQL
  # mysql:
  #   build: ./mysql
  #   restart: always
  #   hostname: mysql
  #   volumes:
  #     - './mysql/mysql_data:/var/lib/mysql'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #   ports:
  #     - '3306:3306'
  #   networks:
  #     - lareferencia-network

  #PostgreSQL
  postgres:
    build: ./postgres
    restart: always
    hostname: postgres
    volumes:
      - './postgres/postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=lrharvester
      - POSTGRES_USER=lrharvester
      - POSTGRES_DB=lrharvester
    ports:
      - '5432:5432'
    networks:
      - lareferencia-network

  #Elasticsearch
  elasticsearch:
    build: ./elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    mem_limit: 4g
    mem_reservation: 2g
    ulimits:
      #memlock:
      #  soft: -1
      #  hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - lareferencia-network

  #Kibana
  kibana:
    hostname: kibana
    build: ./kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - lareferencia-network

  #Solr
  solr:
    image: "solr:7.3.1"
    restart: always
    hostname: solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr/cores:/opt/solr/server/solr/mycores
    networks:
      - lareferencia-network

  #LaReferencia
  lareferencia:
    build: ./lareferencia
    restart: always
    hostname: lareferencia
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./lareferencia/codigo:/home/lareferencia/codigo
    networks:
      - lareferencia-network
    depends_on:
      - postgres
      - elasticsearch
      - kibana
      - solr
networks:
  lareferencia-network:
    driver: bridge