version: '3'
services:
  mysql:
    image: 'mariadb:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
            - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
