version: '3'
services:
  postgres:
    image: 'postgres:14'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=lrharvester
      - POSTGRES_USER=lrharvester
      - POSTGRES_DB=lrharvester
    ports:
      - '5432:5432'
